version: '3'
services:
  app:
    build: ./
    container_name: movie-api
    environment:
      DB_HOST: db
    networks:
      - default
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: MovieApi
    networks:
      - default
networks:
  default:
    name: movie-api
    driver: bridge
